//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 02:46:15 PM EEST 
//


package com.luxoft.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.luxoft.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.luxoft.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FilterTodo }
     * 
     */
    public FilterTodo createFilterTodo() {
        return new FilterTodo();
    }

    /**
     * Create an instance of {@link UpdateTodo }
     * 
     */
    public UpdateTodo createUpdateTodo() {
        return new UpdateTodo();
    }

    /**
     * Create an instance of {@link Todo }
     * 
     */
    public Todo createTodo() {
        return new Todo();
    }

    /**
     * Create an instance of {@link FilterTodoResponse }
     * 
     */
    public FilterTodoResponse createFilterTodoResponse() {
        return new FilterTodoResponse();
    }

    /**
     * Create an instance of {@link GetTodoResponse }
     * 
     */
    public GetTodoResponse createGetTodoResponse() {
        return new GetTodoResponse();
    }

    /**
     * Create an instance of {@link TodoRequest }
     * 
     */
    public TodoRequest createTodoRequest() {
        return new TodoRequest();
    }

    /**
     * Create an instance of {@link RemoveRequest }
     * 
     */
    public RemoveRequest createRemoveRequest() {
        return new RemoveRequest();
    }

    /**
     * Create an instance of {@link UpdateTodoResponse }
     * 
     */
    public UpdateTodoResponse createUpdateTodoResponse() {
        return new UpdateTodoResponse();
    }

    /**
     * Create an instance of {@link AddTodo }
     * 
     */
    public AddTodo createAddTodo() {
        return new AddTodo();
    }

    /**
     * Create an instance of {@link AddTodoResponse }
     * 
     */
    public AddTodoResponse createAddTodoResponse() {
        return new AddTodoResponse();
    }

}
